# Site settings
title: Pratik Brahma blog
email: 
description: "Deep Learning Blog"
baseurl: ""
url: "http://prprbr.github.io"
github_username:  prprbr

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
