# Site settings
title: Trying to Learn: Both AI and me
email: 
description: "Blog by Pratik Prabhanjan Brahma"
baseurl: ""
url: "http://prprbr.github.io"
github_username:  prprbr
linkedin_username: pratik-prabhanjan-brahma-065b7631

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
